export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="protoku"

plugins=(git)

source $ZSH/oh-my-zsh.sh

# NeoVIM aliases
alias n="nvim"

# GIT aliases
alias gs="git status"
alias ga="git add ."
alias gc="git commit -m"
alias gp="git push -u origin HEAD"
alias gl="git pull"
alias gd="git diff"

# Kubernetes
alias k="kubectl"

# Add a new line after each command output
precmd() {
    precmd() {
        echo "\n"
    }
}

export PATH="/opt/homebrew/opt/node@12/bin:$PATH"
